services:
 nestjs-app:
   build: .
   container_name: nestjs-franchise
   ports:
     - "8080:8080"
   environment:
     - DATABASE_URL=postgresql://kju9038:20180520@172.17.0.1:5433/crawler_db
     - CRAWLER_URL=http://crawler-api:8000
     - JWT_SECRET=20180520
     - PORT=8080
   networks:
     - py-crawler_default
   restart: unless-stopped

networks:
 py-crawler_default:
   external: true